"""empty message

Revision ID: 824c4d44fb1e
Revises: 2758ccf9dd76
Create Date: 2025-10-21 23:47:26.496761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '824c4d44fb1e'
down_revision: Union[str, Sequence[str], None] = '2758ccf9dd76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('quantity', sa.UUID(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
